// <auto-generated />
namespace Northwind.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class setMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201911241840204_setMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
