// <auto-generated />
namespace Northwind.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class ADEDUSER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADEDUSER));
        
        string IMigrationMetadata.Id
        {
            get { return "201911202055336_ADEDUSER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
